# Generated by Django 4.2.29 on 2026-03-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='grupo',
            field=models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('grupo_a', 'Santa Teresita del Niño Jesús'), ('grupo_b', 'San Carlo Acutis'), ('grupo_c', 'San Pier Giorgio'), ('grupo_d', 'San Domingo Savio'), ('grupo_e', 'Beata Chiara Luce Badano'), ('grupo_f', 'Sierva de Dios Clare Crockett'), ('grupo_g', 'Beato Rolando Rivi'), ('grupo_h', 'Siervo de Dios Marcelo Câmara'), ('grupo_i', 'San Luis Gonzaga')], default='sin_asignar', max_length=30, verbose_name='Grupo'),
        ),
    ]
