# Generated by Django 4.2.29 on 2026-03-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0002_conductor_cedula_alter_conductor_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='asistencia_dia_1',
            field=models.BooleanField(default=False, verbose_name='Asistencia día 1'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='asistencia_dia_2',
            field=models.BooleanField(default=False, verbose_name='Asistencia día 2'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='asistencia_dia_3',
            field=models.BooleanField(default=False, verbose_name='Asistencia día 3'),
        ),
    ]
