# Generated by Django 4.2.29 on 2026-03-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0003_conductor_asistencia_dia_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='grupo',
            field=models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('grupo_a', 'Santa Teresita del Niño Jesús'), ('grupo_b', 'San Carlo Acutis'), ('grupo_c', 'San Pier Giorgio'), ('grupo_d', 'San Domingo Savio'), ('grupo_e', 'Beata Chiara Luce Badano'), ('grupo_f', 'Sierva de Dios Clare Crockett'), ('grupo_g', 'Beato Rolando Rivi'), ('grupo_h', 'Siervo de Dios Marcelo Câmara'), ('grupo_i', 'San Luis Gonzaga'), ('grupo_j', 'Sierva de Dios Chiaria Corbella Petrillo')], default='sin_asignar', max_length=30, verbose_name='Grupo'),
        ),
    ]
